n=int(input('Digite um numero: '))
print(type(n))
m=float(input('Digite um numero quebrado: '))
print(type(m))
o=bool(input('Digite digite verdadeiro ou falso: '))
print(type(o))
p=bool(input('Digite algo: '))
print(type(p))
q=str(input('Digite uma palavra: '))
print(type(q))